import { Metadata } from "next";

import "../styles/global.css";
import Header from "../components/header";

export const metadata: Metadata = {
  title: { template: "%s | Next Movies", default: "Next Movies" },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
